// Family-friendly drawing prompts curated from the vocabulary supplied for the game.
// Adult, hateful, graphic, political, religious, and otherwise sensitive entries are
// intentionally omitted. Keep entries explicit so additions can be reviewed safely.
export const BUILT_IN_WORDS = [
  "cat",
  "dog",
  "sun",
  "tree",
  "book",
  "car",
  "house",
  "ball",
  "bird",
  "fish",
  "moon",
  "star",
  "flower",
  "apple",
  "banana",
  "chair",
  "table",
  "door",
  "window",
  "phone",
  "clock",
  "bed",
  "shoe",
  "hat",
  "eye",
  "nose",
  "ear",
  "mouth",
  "hand",
  "foot",
  "heart",
  "rain",
  "snow",
  "cloud",
  "pizza",
  "cake",
  "ice cream",
  "milk",
  "water",
  "juice",
  "bread",
  "cheese",
  "egg",
  "chicken",
  "cow",
  "pig",
  "horse",
  "sheep",
  "duck",
  "rabbit",
  "mouse",
  "lion",
  "tiger",
  "elephant",
  "monkey",
  "bear",
  "snake",
  "spider",
  "butterfly",
  "bee",
  "ant",
  "grass",
  "leaf",
  "rock",
  "mountain",
  "river",
  "ocean",
  "beach",
  "sand",
  "fire",
  "ice",
  "wind",
  "rainbow",
  "bridge",
  "road",
  "bike",
  "bus",
  "train",
  "plane",
  "boat",
  "ship",
  "helicopter",
  "truck",
  "taxi",
  "school",
  "hospital",
  "church",
  "store",
  "bank",
  "hotel",
  "restaurant",
  "library",
  "park",
  "zoo",
  "farm",
  "city",
  "town",
  "country",
  "world",
  "space",
  "pen",
  "pencil",
  "paper",
  "scissors",
  "glue",
  "tape",
  "ruler",
  "eraser",
  "crayon",
  "paint",
  "brush",
  "camera",
  "computer",
  "television",
  "radio",
  "music",
  "song",
  "dance",
  "movie",
  "game",
  "toy",
  "doll",
  "robot",
  "puzzle",
  "blocks",
  "kite",
  "balloon",
  "gift",
  "box",
  "bag",
  "basket",
  "bottle",
  "cup",
  "plate",
  "bowl",
  "spoon",
  "fork",
  "knife",
  "pot",
  "pan",
  "stove",
  "oven",
  "microwave",
  "refrigerator",
  "sink",
  "toilet",
  "shower",
  "bathtub",
  "towel",
  "soap",
  "shampoo",
  "toothbrush",
  "toothpaste",
  "mirror",
  "comb",
  "hair",
  "face",
  "teeth",
  "tongue",
  "finger",
  "toe",
  "arm",
  "leg",
  "knee",
  "elbow",
  "shoulder",
  "neck",
  "back",
  "stomach",
  "chest",
  "head",
  "brain",
  "blood",
  "bone",
  "skin",
  "happy",
  "sad",
  "angry",
  "scared",
  "love",
  "friend",
  "family",
  "mother",
  "father",
  "sister",
  "brother",
  "baby",
  "child",
  "man",
  "woman",
  "boy",
  "girl",
  "teacher",
  "doctor",
  "nurse",
  "police",
  "firefighter",
  "chef",
  "farmer",
  "student",
  "bicycle",
  "waterfall",
  "birthday cake",
  "telescope",
  "lighthouse",
  "volcano",
  "skateboard",
  "microscope",
  "compass",
  "thermometer",
  "calculator",
  "keyboard",
  "headphones",
  "backpack",
  "umbrella",
  "sunglasses",
  "wristwatch",
  "necklace",
  "bracelet",
  "earrings",
  "wallet",
  "passport",
  "suitcase",
  "airplane ticket",
  "hotel room",
  "swimming pool",
  "tennis court",
  "basketball hoop",
  "soccer goal",
  "baseball bat",
  "golf club",
  "bowling ball",
  "ice skates",
  "roller skates",
  "surfboard",
  "snowboard",
  "parachute",
  "hot air balloon",
  "submarine",
  "rocket ship",
  "space station",
  "astronaut",
  "alien",
  "dinosaur",
  "skeleton",
  "vampire",
  "werewolf",
  "witch",
  "wizard",
  "dragon",
  "unicorn",
  "mermaid",
  "fairy",
  "castle",
  "knight",
  "princess",
  "prince",
  "king",
  "queen",
  "crown",
  "treasure chest",
  "pirate ship",
  "treasure map",
  "compass rose",
  "anchor",
  "sailboat",
  "yacht",
  "cruise ship",
  "lifeboat",
  "life jacket",
  "fire extinguisher",
  "smoke detector",
  "first aid kit",
  "ambulance",
  "stretcher",
  "wheelchair",
  "crutches",
  "bandage",
  "stethoscope",
  "syringe",
  "medicine bottle",
  "prescription",
  "x-ray",
  "dentist chair",
  "toothache",
  "headache",
  "fever",
  "sneeze",
  "cough",
  "yawn",
  "stretch",
  "exercise",
  "yoga pose",
  "meditation",
  "treadmill",
  "dumbbell",
  "jump rope",
  "hula hoop",
  "trampoline",
  "swing set",
  "slide",
  "seesaw",
  "merry-go-round",
  "sandbox",
  "jungle gym",
  "monkey bars",
  "hopscotch",
  "hide and seek",
  "tag",
  "board game",
  "chess board",
  "checkers",
  "playing cards",
  "dice",
  "dominoes",
  "jigsaw puzzle",
  "crossword puzzle",
  "sudoku",
  "video game controller",
  "joystick",
  "arcade machine",
  "pinball machine",
  "slot machine",
  "roulette wheel",
  "poker chips",
  "trophy",
  "medal",
  "ribbon",
  "certificate",
  "diploma",
  "graduation cap",
  "school bus",
  "blackboard",
  "whiteboard",
  "projector",
  "globe",
  "atlas",
  "encyclopedia",
  "dictionary",
  "thesaurus",
  "bookmark",
  "reading glasses",
  "magnifying glass",
  "binoculars",
  "periscope",
  "kaleidoscope",
  "prism",
  "test tube",
  "beaker",
  "bunsen burner",
  "periodic table",
  "solar system",
  "constellation",
  "shooting star",
  "comet",
  "asteroid",
  "galaxy",
  "black hole",
  "satellite",
  "space shuttle",
  "control tower",
  "runway",
  "baggage claim",
  "departure board",
  "boarding pass",
  "flight attendant",
  "pilot",
  "air traffic controller",
  "mechanic",
  "electrician",
  "plumber",
  "carpenter",
  "architect",
  "engineer",
  "scientist",
  "researcher",
  "professor",
  "librarian",
  "accountant",
  "lawyer",
  "judge",
  "courtroom",
  "gavel",
  "scales of justice",
  "handcuffs",
  "jail cell",
  "security camera",
  "metal detector",
  "fingerprint",
  "evidence",
  "witness stand",
  "jury box",
  "briefcase",
  "filing cabinet",
  "paper clip",
  "stapler",
  "hole punch",
  "shredder",
  "photocopier",
  "accordion", "acorn", "air conditioner", "airbag", "airport", "alarm",
  "albatross", "alligator", "almond", "alpaca", "anaconda", "anglerfish",
  "animation", "anteater", "antelope", "antenna", "anthill", "anvil",
  "apartment", "applause", "apple pie", "apricot", "aquarium", "arch",
  "armadillo", "arrow", "artist", "attic", "audience", "autograph", "avocado",
  "baboon", "backflip", "bacon", "badger", "bagel", "bagpipes", "baguette",
  "bakery", "balance", "balcony", "ballet", "bamboo", "bandana", "banjo",
  "barbecue", "barcode", "barn", "barrel", "basketball", "beak", "bean",
  "bean bag", "beanie", "beanstalk", "beaver", "beetle", "bell", "bell pepper",
  "belt", "bench", "billiards", "bingo", "birch", "bird bath", "biscuit",
  "blackberry", "blanket", "blender", "blimp", "blizzard", "blowfish",
  "blueberry", "boar", "bobsled", "bookcase", "bookshelf", "boomerang", "boots",
  "bottle flip", "bow", "bowling", "braces", "branch", "breakfast", "brick",
  "broccoli", "broom", "brownie", "bubble", "bubble gum", "bucket", "building",
  "bulldozer", "bungee jumping", "bunk bed", "bunny", "burrito", "bus driver",
  "bus stop", "butter", "button", "cabin", "cabinet", "cactus", "calendar",
  "camel", "campfire", "camping", "can opener", "canary", "candle", "canyon",
  "cape", "cappuccino", "car wash", "cardboard", "carnival", "carpet", "carrot",
  "cartoon", "cash", "catapult", "caterpillar", "catfish", "cauldron",
  "cauliflower", "cave", "ceiling fan", "cell phone", "cello", "centaur",
  "centipede", "chain", "chalk", "chameleon", "champion", "chandelier", "charger",
  "cheeseburger", "cheesecake", "cheetah", "cherry", "cherry blossom", "chess",
  "chestnut", "chihuahua", "chime", "chimney", "chimpanzee", "chinchilla",
  "chocolate", "chopsticks", "circle", "circus", "clarinet", "classroom", "claw",
  "clay", "cliff", "cloak", "clothes hanger", "clover", "clown", "clownfish",
  "coach", "coast", "coat", "cobra", "cockroach", "coconut", "cocoon", "coffee",
  "coffee shop", "coin", "collar", "comedy", "comic book", "community",
  "computer mouse", "concert", "cone", "confused", "console", "continent",
  "controller", "cookie", "cookie jar", "coral", "coral reef", "cork",
  "corkscrew", "corn", "corn dog", "cornfield", "cotton candy", "cowbell",
  "cowboy", "coyote", "crab", "crate", "croissant", "crow", "crystal", "cube",
  "cucumber", "cupboard", "cupcake", "curry", "curtain", "cushion", "cylinder",
  "cymbal", "daisy", "dalmatian", "dandelion", "darts", "dashboard", "deer",
  "delivery", "desert", "dessert", "detective", "dew", "diamond", "diaper",
  "dinner", "dishcloth", "display", "dock", "doghouse", "dollhouse", "dolphin",
  "dome", "donkey", "doorknob", "dough", "dragonfly", "drawer", "dress", "drum",
  "drum kit", "duct tape", "dwarf", "eagle", "earbuds", "earthquake", "eclipse",
  "eel", "eggplant", "electric car", "electric guitar", "elevator", "emerald",
  "emoji", "engine", "equator", "espresso", "evening", "exam", "excavator",
  "explosion", "eyebrow", "eyelash", "fabric", "face paint", "factory",
  "fake teeth", "fast food", "faucet", "feather", "fence", "fern", "festival",
  "field", "figurine", "fire alarm", "fire hydrant", "fire truck", "fireball",
  "firecracker", "firefly", "fireplace", "firework", "fish bowl", "fisherman",
  "flag", "flagpole", "flamingo", "flashlight", "flask", "flock", "floppy disk",
  "florist", "flute", "fly swatter", "flying pig", "fog", "foil", "folder",
  "forehead", "forest", "fort", "fossil", "fountain", "fox", "frame", "freckles",
  "freezer", "fridge", "fries", "frog", "frosting", "fruit", "full moon",
  "furniture", "garden", "gardener", "garlic", "gas mask", "generator", "genie",
  "geography", "geyser", "ghost", "giant", "giraffe", "gladiator", "glasses",
  "glitter", "glove", "glowstick", "glue stick", "gnome", "goat", "goblin",
  "goldfish", "golf cart", "goose", "gorilla", "graffiti", "grapefruit", "grapes",
  "grasshopper", "gravel", "grill", "guinea pig", "guitar", "gumball",
  "gummy bear", "hairbrush", "haircut", "ham", "hamburger", "hammer", "hammock",
  "hamster", "handshake", "hanger", "harbor", "hard hat", "harmonica", "harp",
  "hazelnut", "headband", "headboard", "hedgehog", "helmet", "hen", "hero",
  "hexagon", "high five", "highway", "hill", "hippo", "hive", "hockey", "honey",
  "honeycomb", "hoof", "hook", "horizon", "horn", "hose", "hot chocolate",
  "hot dog", "hot sauce", "hourglass", "hovercraft", "hummingbird", "hurdle",
  "hut", "hyena", "ice cream truck", "iceberg", "icicle", "island", "ivy",
  "jacket", "jackhammer", "jaguar", "jelly", "jellyfish", "jester", "jet ski",
  "juggle", "jungle", "kangaroo", "karaoke", "karate", "kazoo", "kebab",
  "ketchup", "kettle", "key", "kitten", "kiwi", "koala", "kraken", "ladder",
  "ladybug", "lake", "lamb", "lamp", "landscape", "lantern", "laptop", "laser",
  "laundry", "lava", "lava lamp", "lawn mower", "lemon", "lemonade", "lemur",
  "leprechaun", "lettuce", "light bulb", "lily", "lily pad", "lime", "limousine",
  "lips", "lipstick", "lizard", "llama", "lobster", "lollipop", "luggage",
  "lumberjack", "macaroni", "magazine", "magic wand", "magician", "magma",
  "magnet", "magnifier", "mailbox", "mall", "mammoth", "manatee", "mansion",
  "mantis", "map", "maracas", "marathon", "marble", "market", "marshmallow",
  "mascot", "mask", "matchbox", "mattress", "maze", "meatball", "meerkat",
  "megaphone", "melon", "meteorite", "milkshake", "mime", "miner", "mini golf",
  "minivan", "mint", "mohawk", "mole", "money", "moose", "mop", "morning",
  "mosquito", "moss", "moth", "motorbike", "motorcycle", "mousetrap", "muffin",
  "mug", "museum", "mushroom", "mustache", "mustard", "nachos", "nail file",
  "napkin", "narwhal", "nest", "newspaper", "night", "noodle", "notebook",
  "notepad", "notification", "nugget", "nutcracker", "nutmeg", "oar",
  "observatory", "octagon", "octopus", "office", "omelet", "onion", "opera",
  "orange", "orangutan", "orbit", "orca", "orchestra", "orchid", "origami",
  "ostrich", "otter", "oval", "owl", "oyster", "paddle", "pajamas", "palace",
  "palette", "palm tree", "pancake", "panda", "panther", "papaya", "paper bag",
  "parade", "parakeet", "parrot", "pasta", "pastry", "patio", "pavement", "paw",
  "peach", "peacock", "peanut", "pear", "peas", "pelican", "pencil case",
  "pencil sharpener", "pendulum", "penguin", "peninsula", "pepper", "pepperoni",
  "perfume", "pet shop", "photo frame", "photograph", "piano", "pickaxe",
  "pickle", "picnic", "pie", "pigeon", "piggy bank", "pillow", "pillow fight",
  "pine cone", "pineapple", "pinwheel", "pirate", "planet", "playground",
  "plunger", "pogo stick", "polar bear", "popcorn", "poppy", "porch",
  "porcupine", "portal", "postcard", "pot of gold", "potato", "potion", "pretzel",
  "price tag", "printer", "pudding", "puddle", "puffin", "puma", "pumpkin",
  "puppet", "pyramid", "quill", "quilt", "quokka", "raccoon", "racecar", "radar",
  "radish", "raft", "raincoat", "raindrop", "rainforest", "raisin", "rake",
  "ramp", "raspberry", "ravioli", "receptionist", "rectangle", "recycling",
  "reindeer", "remote control", "rhinoceros", "rice", "ring", "robin", "rocket",
  "rooster", "rose", "rubber duck", "ruby", "rug", "saddle", "safari", "salad",
  "salmon", "sand castle", "sandstorm", "sandwich", "sauce", "sausage",
  "saxophone", "scarecrow", "scarf", "scoop", "screw", "scuba diver",
  "sculpture", "sea lion", "seagull", "seahorse", "seashell", "seat belt",
  "seaweed", "semicircle", "sewing machine", "shadow", "shark", "shopping cart",
  "shovel", "skateboarder", "skier", "skyline", "skyscraper", "slinky", "sloth",
  "snail", "snowball", "snowflake", "snowman", "soccer ball", "solar panel",
  "sombrero", "soup", "space suit", "spaceship", "spaghetti", "spatula", "speaker",
  "sphinx", "spinach", "spiral", "sponge", "sports stadium", "spring", "sprinkler",
  "square", "squid", "squirrel", "stamp", "starfish", "starfruit", "statue",
  "stereo", "stingray", "stop sign", "stork", "storm", "strawberry", "street",
  "stylus", "subway", "sunburn", "sunflower", "sunrise", "supermarket", "sushi",
  "swamp", "swan", "sweater", "table tennis", "tablecloth", "tablet", "taco",
  "tadpole", "tailor", "tangerine", "teapot", "teddy bear", "tennis racket",
  "tent", "throne", "thunderstorm", "ticket", "time machine", "tiramisu",
  "tissue box", "toad", "toast", "toaster", "tomato", "toolbox", "toothpick",
  "top hat", "tornado", "tortoise", "toucan", "tow truck", "tractor",
  "traffic light", "trailer", "trapdoor", "trash can", "treehouse", "triangle",
  "tricycle", "tripod", "trombone", "tropical island", "trumpet", "tuba",
  "tugboat", "tuna", "tunnel", "turkey", "turnip", "turtle", "tuxedo", "twig",
  "ukulele", "unibrow", "unicycle", "universe", "vacation", "vacuum", "valley",
  "vanilla", "vegetable", "veterinarian", "video game", "village", "violin",
  "volleyball", "vortex", "waffle", "waiter", "wallpaper", "walnut", "walrus",
  "warehouse", "water cycle", "water gun", "wave", "weather", "website", "welder",
  "whale", "wheelbarrow", "whisk", "whistle", "wig", "willow", "windmill",
  "windshield", "wine glass", "wing", "winter", "wireless router", "wolf",
  "woodpecker", "wool", "wrapping paper", "wreath", "wrench", "xylophone",
  "yardstick", "yeti", "yo-yo", "yogurt", "zebra", "zeppelin", "zigzag",
  "zipline", "zipper", "zombie",
  "hawk", "sparrow", "seal", "crocodile", "worm", "grape", "watermelon",
  "mango", "plum", "burger", "donut", "noodles", "tea", "sofa", "monitor",
  "lock", "screwdriver", "rope", "fan", "sock", "shirt", "pants", "microphone",
  "police car", "roller coaster", "police officer", "musician", "treasure", "gold",
  "lightning", "football", "soccer", "tennis", "baseball", "golf", "swimming",
  "surfing", "skiing", "battery", "paintbrush",
] as const
